[project]
name = "deep-learning"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "jupyter>=1.1.1",
    "notebook>=7.5.6",
    "pytest>=9.0.3",
]

[project.scripts]
deep-learning = "deep_learning:main"

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"
